### PR TITLE
Fix for #1242

### PR DESCRIPTION
**Pull request by KalyanaChakravarthi**
Fixed issue of MIDL_INTERFACE classes tokenized as Labels.
Added check for c style languages(c,cpp,cs) to identify the Labels properly.
Corrected the input and output files containing 'public' keyword misspelled.

### CODE REVIEW

**Comment by mihaipopescu** [comment]
test this please

**Comment by KalyanaChakravarthi** [comment]
test this please

**Comment by agandavarapu-rythmos** [comment]
test this please

**Comment by mihaipopescu** [comment]
test this please

**Comment by KalyanaChakravarthi** [comment]
Closing this pull request as created pull request #78 for the same issue.

**Pull request closed without merging**
