### PR TITLE
Fixed issue of bad tokenization of references 

### PR DESCRIPTION
**Pull request by KalyanaChakravarthi**
Fixed wrong spacing around c++ reference operator for an external function forward declared inside another function

### CODE REVIEW

**Comment by Rassi** [comment]
I have added tests (60039) for a missing case and a regression.
The regression concerns function prototypes, but since they are macros Uncrustify will probably interpret them as function calls. There is a way to force them to be function prototypes using the configuration option PROTO_WRAP, as seen in Uncrustify.Cpp.cfg.

@mihaipopescu have more insight into this. Feel free to add more information.

**Comment by hschlichter** [comment]
test this please

**Comment by mihaipopescu** [comment]
@KalyanaChakravarthi please take a look at what upstream said here https://github.com/uncrustify/uncrustify/issues/1398

**Comment by KalyanaChakravarthi** [comment]
@mihaipopescu we will look into this.

**Pull request merged**
