### PR TITLE
Fixes/indente 4 to 1 line func

### PR DESCRIPTION
**Pull request by spuppala-rythmos**

### CODE REVIEW

**Comment by spuppala-rythmos** [comment]
All the diffs generated seems to be valid 

[changes_77.zip](https://github.com/Unity-Technologies/uncrustify/files/1593082/changes_77.zip)

**Review by hschlichter — APPROVED** [review]
Looks good. Updating the diff checker and will wait for green build.

**Comment by hschlichter** [comment]
jenkins-builder: test this please

**Comment by spuppala-rythmos** [comment]
test this please

**Comment by hschlichter** [comment]
jenkins-builder: test this please

**Comment by hschlichter** [comment]
jenkins-builder: test this please

**Pull request merged**
