### PR TITLE
DO NOT MERGE! Fixes/test build notifications

### PR DESCRIPTION
**Pull request by Rassi**
This is a test PR for setting up notifications from our build system. Please ignore.

### CODE REVIEW

**Comment by Rassi** [comment]
retest this please

**Comment by Rassi** [comment]
retest this please

**Comment by agandavarapu-rythmos** [comment]
Thanks for the regressions. We will get back to you as soon as possible.

**Comment by Rassi** [comment]
Hi @aneesh1127. This PR is only for testing purposes. You might be looking for #41 :)

**Comment by Rassi** [comment]
the "retest this please" comments are for our build system, so please ignore them :)

**Comment by Rassi** [comment]
retest this please

**Comment by Rassi** [comment]
retest this please

**Comment by Rassi** [comment]
retest this please

**Comment by unitydevtools** [comment]
Can one of the admins verify this patch?

**Comment by Rassi** [comment]
test this please

**Comment by Rassi** [comment]
test this please

**Comment by Rassi** [comment]
unity-diff-checker test this please

**Comment by Rassi** [comment]
unity-diff-checker test this please

**Pull request closed without merging**
