### PR TITLE
UnitTest++ support

### PR DESCRIPTION
**Pull request by mihaipopescu**
We need to implement support for [UnitTest++](https://github.com/unittest-cpp/unittest-cpp) framework.

First off we can start by supporting `TEST_FIXTURE` macro to be able to properly format them (eg. add newline before `{` as in this newly added test).

Other macros are needed, usually everything that matches:
```
TEST
\w+_TEST
\w+_TEST_\w+
```

Let's see how this goes and what is the effect on unity codebase.

### CODE REVIEW

**Comment by hschlichter** [comment]
jenkins-builder: test this please

**Comment by mihaipopescu** [comment]
If the diff is fine I guess we can merge it, right @hschlichter ?

**Comment by hschlichter** [comment]
jenkins-builder: test this please

**Comment by mihaipopescu** [comment]
jenkins-builder: test this please

**Review by hschlichter — APPROVED** [review]

**Comment by hschlichter** [comment]
test this please

**Pull request merged**
