### PR TITLE
fixes #1264

### PR DESCRIPTION
**Pull request by spuppala-rythmos**
Currently there is no indentation of CT_MEMBER
to make the indent we are pushing the CT_MEMBER into stack and pressing.

will be adding more details/description regarding changes based on PR diffs

### CODE REVIEW

**Comment by KalyanaChakravarthi** [comment]
test this please

**Comment by spuppala-rythmos** [comment]
unity-diff-checker test this please

**Comment by agandavarapu-rythmos** [comment]
test this please

**Comment by spuppala-rythmos** [comment]
test this please

**Comment by spuppala-rythmos** [comment]
unity-diff-checker test this please

**Comment by spuppala-rythmos** [comment]
test this please

**Comment by KalyanaChakravarthi** [comment]
test this please

**Comment by hschlichter** [comment]
Seems there is a problem with the travis build.
```
Problem with Results/help.txt.sed
use: diff tests/cli/Results/help.txt.sed tests/cli/Output/help.txt to find out why
72c72
< There are currently 618 options and minimal documentation.
---
> There are currently 617 options and minimal documentation.
```

**Comment by agandavarapu-rythmos** [comment]
test this please

**Comment by agandavarapu-rythmos** [comment]
test this please

**Review by hschlichter — APPROVED** [review]
Looks good. Builds are green.

**Pull request merged**
