### PR TITLE
Fix for extra double quote character in #include

### PR DESCRIPTION
**Pull request by pkusumaraju-rythmos-zz**
Introduced new option mod_include_strict_parsing.
It will support extra characters after the include is closed. (ingore mode by default) and report an error

### CODE REVIEW

**Comment by unitydevtools** [comment]
Can one of the admins verify this patch?

**Comment by satishp87** [comment]
test this please

**Comment by spuppala-rythmos** [comment]
test this please

**Comment by pkusumaraju-rythmos-zz** [comment]
test this please

**Comment by pkusumaraju-rythmos-zz** [comment]
test this please

**Review by hschlichter — CHANGES_REQUESTED** [review]
Is the tests for this new option not included?

**Comment by pkusumaraju-rythmos-zz** [comment]
we have added test case

**Comment by spuppala-rythmos** [comment]
@hschlichter we have added the test case with option disabled. 
 if we enable the option uncrustify will terminate for this example, which is expected.

**Review by hschlichter — APPROVED** [review]

**Pull request merged**
