### PR TITLE
fix UNI-19644 regression, improve test case

### PR DESCRIPTION
**Pull request by aet**
restores a change from 34890b28aced794384dac299fde527ef3625422a that was lost during upstream merge that happened shortly after that

### CODE REVIEW

**Comment by aet** [comment]
@mihaipopescu @guy-maurel I'm not sure which way to go on fixing a test regression. For some reason there's a CS test 10033 that's now regressing, but it is parsing objective-c++ file.

I'm getting the expected test result if I run the test with the configuration in question manually OR just override "-DTEST_LANG=cs" from the ctest into "-DTEST_LANG=oc"

as OC

log_rule2(129): Spacing: first->orig_line is 6, first->orig_col is 75, first->text() is ':', [OC_COLON/NONE] <===>
   second->orig_line is 6, second->orig_col is 76, second->text() '[', [SQUARE_OPEN/OC_MSG] : rule sp_after_send_oc_colon[line 1970]space_text(2370): rule = FORCE @ 1 => 78

as CS

log_rule2(129): Spacing: first->orig_line is 6, first->orig_col is 75, first->text() is ':', [CS_SQ_COLON/CS_SQ_STMT] <===>
   second->orig_line is 6, second->orig_col is 76, second->text() '[', [SQUARE_OPEN/CS_SQ_STMT] : rule sp_before_square[line 823]space_text(2370): rule = IGNORE @ 0 => 76

as CS (without ffd3358e162833ccafcf3e35e6bb48227ee36165)

log_rule2(129): Spacing: first->orig_line is 6, first->orig_col is 75, first->text() is ':', [CS_SQ_COLON/CS_SQ_STMT] <===>
   second->orig_line is 6, second->orig_col is 76, second->text() '[', [SQUARE_OPEN/CS_SQ_STMT] : rule FORCE[line 1951]space_text(2373): rule = FORCE @ 1 => 78

"[TestCase(";", new string[0])]" breaking is a bit special case

log_rule2(129): Spacing: first->orig_line is 11, first->orig_col is 23, first->text() is 'string', [TYPE/CS_SQ_STMT] <===>
   second->orig_line is 11, second->orig_col is 29, second->text() '[', [SQUARE_OPEN/CS_SQ_STMT] : rule sp_after_type[line 1890]space_text(2373): rule = FORCE @ 1 => 30

I think 10033 should be just moved being part of CS tests into OC, no opinion about 10034 / tests/input/cs/asm.h.mm but it does look like it should be there as well, even if it doesn't appear to do anything objective-c++ specific

**Comment by aet** [comment]
for reference, the original commit 24e0d6dd3f3d8aeb486e3ec1c3cff8b80938f60a from issue# 1276

**Comment by guy-maurel** [comment]
I maintain only the https://github.com/uncrustify/uncrustify
There, the test `10033! U11-Cpp.cfg   cs/objc.mm` runs pretty well.
Please take attention that the test needs two passes.
Please test the current git version and report.

**Comment by aet** [comment]
@guy-maurel the reason why I pinged upstream was to raise awareness of the main issue, why are we adding objective-c files into c# test folder and indenting them as c# language (forced by the test suite) and expect them to follow objective-c codepath rules at all times? does the test suite generally do similar things somewhere else?

**Comment by aet** [comment]
@guy-maurel it appear the original objc.mm and asm.h.mm were added in f8b24907b793756f5c0e1f1aa5056bde8240956e  to staging.test, where at the moment the language of the file is not enforced, but autodetected from the file extension like normal uncrustify run does. @satishp87 said he can relocate those files into oc folder in our repo, so we'll go towards that route

**Review by mihaipopescu — APPROVED** [review]

**Comment by guy-maurel** [comment]
Fine.
Push it, I'll will adopt it for the master.

**Pull request merged**
